# -*- coding: utf-8 -*-
"""cse221_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xOROa90hqnVVtNEnkwIBQ87UGTzSyrD9
"""

#Task4
inp = open("inp4.txt","r")
out = open("out4.txt","w")
read = inp.read()
read_1 = (read.split("\n"))
wrk = []

for i in read_1[1:]:
    start, end = i.split()
    wrk += [[int(end),int(start)]]

temp = str(read_1[0].split()[1])

wrk.sort()
q = []
free = int(temp)
works = 0
for j in wrk:
    if free != 0:
        works += 1
        free -= 1
        q += [j[0]]
    else:
        for k in range(len(q)):
            if q[k] <= j[1]:
                q.pop(k)
                q += [j[0]]
                works += 1


out.write(str(works))
out.close()

