# -*- coding: utf-8 -*-
"""cse221_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xOROa90hqnVVtNEnkwIBQ87UGTzSyrD9
"""

#Task1_1
inp = open('/content/inp1_1.txt','r')
out = open('/content/out1_1.txt','w')
a,b = map(int,inp.readline().split(' '))
lst = list(map(int,inp.readline().split(' ')))

def play(lst,b):
  for i in range(len(lst)):
    for j in range(i+1,len(lst)):
      if lst[i]+lst[j]==b:
        return i+1,j+1
  return 'IMPOSSIBLE'

x = play(lst,b)
for i in x:
  out.write('{} '.format(i))

out.close()

#Task1_2
inp = open('/content/inp1_2.txt','r')
out = open('/content/out1_2.txt','w')
a,b = map(int,inp.readline().split(' '))
lst = list(map(int,inp.readline().split(' ')))

def play1(lst,b):
  dict = {}
  for i in range(lst,b):
    x = lst[i]
    y = b-x
    if y in dict:
      return dict[y]+1, i+1
    else:
      dict[x] = i
  return 'IMPOSSIBLE'

x = play(lst,b)
for i in x:
  out.write('{} '.format(i))

out.close()