# -*- coding: utf-8 -*-
"""cse221_Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ETS5FRPYAveXdGAKqwZsOfjQvDMD3_qW
"""

#Task 3
inp = open('/content/input_3.txt','r')
out = open('/content/output_3.txt','w')
read = int(inp.readline())
read_1 = list(map(int,inp.readline().split()))

def permu(arr):
  lnth = len(arr)
  if lnth <= 1:
    return 0

  mid = lnth // 2
  value_left = arr[:mid]
  value_right= arr[mid:]
  sum_invers = permu(value_left) + permu(value_right)
  i = 0
  j = 0
  k = 0
  while i < len(value_left) and j < len(value_right):
    if value_left[i] > value_right[j]:
      sum_invers += len(value_left) - i
      arr[k] =value_right[j]
      j += 1
    else:
      arr[k] =value_left[i]
      i += 1
    k += 1

  while i < len(value_left):
    arr[k] =value_left[i]
    i += 1
    k += 1

  while j < len(value_right):
    arr[k] = value_right[j]
    j += 1
    k += 1
  return sum_invers

permu = permu(read_1)

out.write(str(permu))
out.close()

