# -*- coding: utf-8 -*-
"""cse221_Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ETS5FRPYAveXdGAKqwZsOfjQvDMD3_qW
"""

#Task 2
inp = open('/content/input_2.txt','r')
out = open('/content/output_2.txt','w')
read = inp.readline()
read_1 = list(map(int,inp.readline().split(' ')))

def maxSort(arr):
  if len(arr) <= 1:
    return arr[0]
  else:
    mid = len(arr)//2
    a1 = maxSort(arr[:mid])
    a2 = maxSort(arr[mid:])
    if a1>a2:
      return a1
    else:
      return a2

max = maxSort(read_1)

out.write(str(max))

out.close()

