# -*- coding: utf-8 -*-
"""cse221_Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ETS5FRPYAveXdGAKqwZsOfjQvDMD3_qW
"""

#Task 4
inp = open('/content/input_4.txt', 'r')
out = open('/content/output_4.txt', 'w')

read = int(inp.readline())
read_1 = list(map(int, inp.readline().split()))


def max_value(vals):
    vals.sort(reverse=True)
    max_sum_value = float('-inf')

    for i in range(read - 1):
        for j in range(i + 1, read):
            current_sum_value = vals[i] + vals[j] ** 2
            if current_sum_value > max_sum_value:
                max_sum_value = current_sum_value

    return max_sum_value

max_sum_value = max_value(read_1)

out.write(str(max_sum_value))
out.close()

