# -*- coding: utf-8 -*-
"""cse221_Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ETS5FRPYAveXdGAKqwZsOfjQvDMD3_qW
"""

#Task 6
inp = open('/content/input_6.txt', 'r')
out = open('/content/output_6.txt', 'w')

total = int(inp.readline().split()[0])
val = list(map(int, inp.readline().split()))
qur = int(inp.readline().split()[0])

def sml_num(arr, k):
    if len(arr) == 1:
        return arr[0]
    a = arr[0]
    b = [x for x in arr[1:] if x <= a]
    c = [x for x in arr[1:] if x > a]
    if k <= len(b):
        return sml_num(b, k)
    elif k == len(b) + 1:
        return a
    else:
        return sml_num(c, k - len(b) - 1)

for q in range(qur):
    K = int(inp.readline())
    sml_val = sml_num(val, K)
    out.write(str(sml_val) + '\n')

inp.close()
out.close()