# -*- coding: utf-8 -*-
"""cse221 lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fx-VO8LA_RxjyhXlqDh9o6QvMl3TEkdF
"""

#Task 1a
inp = open('/content/input1a.txt','r')
out = open('/content/output1a.txt','w')
read = inp.readline()
read1 = inp.readlines()

for i in read1:
  j = i.strip('\n')
  if int(j)%2 == 0:
    out.write('{} is an Even number.\n'.format(j))
  else:
    out.write('{} is an Odd number.\n'.format(j))

inp.close()
out.close()

