# -*- coding: utf-8 -*-
"""cse221 lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fx-VO8LA_RxjyhXlqDh9o6QvMl3TEkdF
"""

#Task 3
inp = open('/content/input3.txt','r')
out = open('/content/output3.txt','w')
read = inp.readline()
id = inp.readline().strip('\n').split(' ')
mark = inp.readline().split(' ')

for i in range(1,int(read)):
  ind = i
  while ind>0:
    if int(mark[ind]) > int(mark[ind-1]):
      mark[ind], mark[ind-1] = mark[ind-1], mark[ind]
      id[ind], id[ind-1] = id[ind-1], id[ind]

    elif int(mark[ind]) == int(mark[ind-1]):
      if id[ind] < id[ind-1]:
        id[ind], id[ind-1] = id[ind-1], id[ind]

    ind -= 1

for i in range(int(read)):
  out.write('ID: {} Mark: {}\n'.format(id[i],mark[i]))

out.close()

