# -*- coding: utf-8 -*-
"""cse221 lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fx-VO8LA_RxjyhXlqDh9o6QvMl3TEkdF
"""



#Task 1b
inp = open('/content/input1b.txt','r')
out = open('/content/output1b.txt','w')
read = inp.readline()
read1 = inp.readlines()

for i in read1:
  num1, operator, num2 = i[10:].split(' ')
  if operator == '+':
    j = int(num1)+int(num2)
    out.write(f'The result of {i[10:].strip()} is {j}\n')
  elif operator == '-':
    j = int(num1)-int(num2)
    out.write(f'The result of {i[10:].strip()} is {j}\n')
  elif operator == '*':
    j = int(num1)*int(num2)
    out.write(f'The result of {i[10:].strip()} is {j}\n')
  elif operator == '/':
    j = int(num1)/int(num2)
    out.write(f'The result of {i[10:].strip()} is {j}\n')

inp.close()
out.close()