# -*- coding: utf-8 -*-
"""cse221 lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fx-VO8LA_RxjyhXlqDh9o6QvMl3TEkdF
"""

#Task 2
inp = open('/content/input2.txt','r')
out = open('/content/output2.txt','w')
read = inp.readline()
read1 = list(map(int,inp.readline().split(' ')))


def bubbleSort(arr):
  for i in range(len(arr)-1):
    flag = 0
    for j in range(len(arr)-i-1):
      if arr[j] > arr[j+1]:
        arr[j], arr[j+1] = arr[j+1], arr[j]
        flag = 1

    if flag == 0:
      break
  return arr

a = bubbleSort(read1)
for i in a:
  out.write('{} '.format(i))

out.close()

#In the best case, the list is already sorted. So, after we come out of the inner 'for' loop, due to the flag we can see that no changes
#were made thus recognizing that the list is already sorted. So, it just breaks out of the loops. That means the inner loop executed for
#n times and the outer loop executed for 1 time. Thus making the time complexity θ(n).