# -*- coding: utf-8 -*-
"""cse221 lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fx-VO8LA_RxjyhXlqDh9o6QvMl3TEkdF
"""

#Task 3
inp = open('/content/input4.txt','r')
out = open('/content/output4.txt','w')
read = int(inp.readline())
dept = [inp.readline().strip() for i in range(1,read+1)]

for i in range(len(dept)):
  for j in range(len(dept)-i-1):
    dept_1 = dept[j].split(' ')
    dept_2 = dept[j+1].split(' ')
    if dept_1[0] > dept_2[0]:
      dept[j],dept[j+1] = dept[j+1],dept[j]
    elif dept_1[0] == dept_2[0] and dept_1[-1] < dept_2[-1]:
      dept[j],dept[j+1] = dept[j+1],dept[j]

for i in dept:
  out.write(i+'\n')

out.close()